<?xml version="1.0"?>
<package format="3">
  <name>vacuum_bot_description</name>
  <version>0.0.0</version>
  <description>Vacuum Bot Simulation</description>

  <maintainer email="user@todo.todo">Shalini</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>rqt_image_view</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>